trace: true

spring:
  application:
    name: directory

dns:
  hosts:
    root: localhost
server:
  hostname: ${dns.hosts.root}
  ssl:
    client-auth: WANT
    enabled: true
    trust-store: classpath:keystore/truststore.jks
    trust-store-password: changeit
    key-store: classpath:keystore/keystore.jks
    key-store-password: changeit
    key-password: ${server.ssl.key-store-password}
    client-certs-key-alias: ${server.hostname}
    jwk-key-store: classpath:keystore/jwksstore.pfx
    jwk-key-store-password: changeit
    self-signed:
      ca-alias: obri-internal-ca
  port: 8443

jwkms:
  internal-port: 8443
  root: https://jwkms:${jwkms.internal-port}/

am:
  oidc:
    issuerid: ${am.root}/oauth2

#Metrics configuration
metrics:
  port: 8444
  endpoints:
    root: https://metrics-services:${metrics.port}
    endpoint-usage:
      add-entries: ${metrics.endpoints.root}/api/kpi/endpoint-usage/add-entries
    jwts-generation:
      add-entries: ${metrics.endpoints.root}/api/kpi/jwts/jwts-generation/add-entries
    jwts-validation:
      add-entries: ${metrics.endpoints.root}/api/kpi/jwts/jwts-validation/add-entries
